#!/bin/sh

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
export XIM_PROGRAM=/usr/bin/ibus-daemon

export TERM=st-256color

nm-applet &                  # NetworkManager applet
ibus-daemon --xim -d &       # IBus daemon for multiple language input
xscreensaver -no-splash &    # Screensaver
exec --no-startup-id /usr/lib/geoclue-2.0/demos/agent & # Start geoclue (needed for redshift)
blueman-applet &             # Bluetooth applet
lxqt-policykit-agent &
nextcloud --background &     # Nextcloud client
export PATH=/home/andreasziegler/.local/bin/statusbar:$PATH # Add statusbar apps to PATH
safeeyes &                   # Safeeyes reduce and prevent repetitive strain injury (RSI)
